dataset_name: burnscars
data_path: ./data/hls_burn_scars
num_classes: 15
multi_temporal: false
multi_modal: false
bands:
  - B2
  - B3
  - B4
  - B8a
  - B11
  - B12
data_mean:
  - 0.033349706741586264,
  - 0.05701185520536176,
  - 0.05889748132001316,
  - 0.2323245113436119,
  - 0.1972854853760658,
  - 0.11944914225186566,
data_std:
  - 0.02269135568823774,
  - 0.026807560223070237,
  - 0.04004109844362779,
  - 0.07791732423672691,
  - 0.08708738838140137,
  - 0.07241979477437814,
data_loader:
  batch: 2
  num_workers: 0
  pin_memory: False
  prefetch_factor: null
  persistent_workers: False