name: pangaea-bench
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - geopandas
  - numpy>=2.0
  - pillow
  - pytorch>=2.1
  - rasterio
  - scikit-learn
  - tensorboard
  - torchaudio
  - torchvision
  - tqdm
  - tifffile
  - timm
  - einops
  - rioxarray
  - pytorch-cuda=11.8
  - gdown
  - ptflops
  - fastai::opencv-python-headless
  - google-cloud-storage
  - omegaconf
  - pydataverse
  - pytest
  - yacs
  - wandb
  - hydra-core

