encoder_name: CROMA_JOINT_Encoder
foundation_model_name: CROMA_OPTICAL_large
encoder_weights: /geomatics/gpuserver-0/vmarsocci/pretrained_models/CROMA_large.pt
download_url: https://huggingface.co/antofuller/CROMA/resolve/main/CROMA_large.pt
temporal_input: False


num_layers: 24
embed_dim: 1024
input_size: 120

encoder_model_args:
  size: 'large'
  image_resolution: 120

input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8a
    - B9
    - B11
    - B12
  sar:
    - VV
    - VH

output_layers:
  - 3
  - 5
  - 7
  - 11
