encoder_name: GFMSwin_Encoder
foundation_model_name: simmim_finetune_swin_base_img128_window4_100ep
encoder_weights: ./pretrained_models/gfm.pth
download_url: https://zenodo.org/records/8412455/files/SpectralGPT.pth

temporal_input: False

input_size: 128
embed_dim: 1024

encoder_model_args:
  in_chans: 3  
  t_patch_size: 3
  depth: 12
  embed_dim: 128
  img_size: 128    # fixed to 128
  depths: [ 2, 2, 18, 2 ]  
  num_heads: [ 4, 8, 16, 32 ]
  window_size: 4
  patch_size: 4
  mlp_ratio: 4
  only_output_last: True

input_bands:
  optical:
    - B4
    - B3
    - B2

output_layers:
  - 0
  - 1
  - 2
  - 3

