encoder_name: Prithvi_Encoder
foundation_model_name: Prithvi_100M
encoder_weights: /geomatics/gpuserver-0/vmarsocci/pretrained_models/Prithvi_100M.pt
download_url: https://huggingface.co/ibm-nasa-geospatial/Prithvi-100M/resolve/main/Prithvi_100M.pt?download=true
temporal_input: True

num_layers: 12
embed_dim: 768
input_size: 224

encoder_model_args:
  img_size: 224
  in_chans: 6
  embed_dim: 768
  patch_size: 16
  num_heads: 12
  depth: 12
  mlp_ratio: 4
  tubelet_size: 1
  # num_frames: 1 #temporal frames (needed also in the encoder for prithvi)

input_bands:
  optical:
    - B2
    - B3
    - B4
    - B8A
    - B11
    - B12

output_layers:
  - 3
  - 5
  - 7
  - 11
