encoder_name: SpectralGPT_Encoder
foundation_model_name: SpectralGPT
encoder_weights: ./pretrained_models/SpectralGPT.pth
download_url: https://zenodo.org/records/8412455/files/SpectralGPT.pth

temporal_input: False

input_size: 128
embed_dim: 3072   # 768 * (in_chans / t_patch_size)

encoder_model_args:
  in_chans: 12    # number of spectral bands
  t_patch_size: 3
  depth: 12
  embed_dim: 768
  img_size: 128
  num_frames: 1    # number of temporal frames 
  num_heads: 12
  patch_size: 8
  mlp_ratio: 4

input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B11
    - B12

output_layers:
  - 3
  - 5
  - 7
  - 11


