_target_: pangaea.datasets.ai4smallfarms.AI4SmallFarms
dataset_name: AI4SmallFarms
root_path: ./data/ai4smallfarms
download_url: https://phys-techsciences.datastations.nl
auto_download: True

img_size: 496
multi_temporal: False
multi_modal: False

ignore_index: -1
num_classes: 1
classes:
  - Background
  - Crop Field

distribution:
  - 0.72676
  - 0.27324

bands:
  optical:
    - B2 
    - B3
    - B4
    - B8

data_mean:
  optical:
    - 750.2136
    - 1032.7277
    - 1165.1279
    - 2416.0448

data_std:
  optical:
    - 283.3842
    - 332.7280
    - 518.9025
    - 702.3791

data_max:
  optical:
    - 10806.0
    - 10167.0
    - 9992.0
    - 10088.0

data_min:
  optical:
    - 1.0
    - 9.0
    - 1.0
    - 66.0