_target_: pangaea.datasets.biomassters.BioMassters
dataset_name: BioMassters
root_path: ./data/Biomassters
download_url: 
auto_download: False
img_size: 256
temp: 6 #6 (select month to use if single temporal (multi_temporal : 1))
multi_temporal: 12
multi_modal: True

# classes
ignore_index: -1
num_classes: 1
classes:
  - regression
distribution:
  - 1.
#   - 0.2
#   - 0.2
#   - 0.2
#   - 0.2
#   - 0.2

bands:
  optical:
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B11
    - B12
    - CLP
  sar:
    - VV #set band name to match the input band name of the model e.g. VV for CROMA, ASC_VV for DOFA
    - VH #set band name to match the input band name of the model e.g. VH for CROMA, ASC_VH for DOFA
    - DSC_VV
    - DSC_VH

# TODO: add mean and std normalization values 
data_mean:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  sar: [0, 0, 0, 0]

data_std:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  sar: [0, 0, 0, 0]
 
data_min:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
  sar: [-25, -62, -25, -60]

data_max:
  optical: [19616., 18400., 17536., 17097., 16928., 16768., 16593., 16492., 15401., 15226.,   255.]
  sar: [29,  28,  30,  22]
