_target_: pangaea.datasets.fivebillionpixels.FiveBillionPixels
dataset_name: FiveBillionPixels
root_path: /geomatics/gpuserver-1/vmarsocci/FiveBillionPixels/cropped
download_url: False 
auto_download: False
use_cmyk: False

img_size: 520
multi_temporal: False
multi_modal: False

# classes
ignore_index: 0
num_classes: 25
classes:
- unlabeled
- industrial area
- paddy field
- irrigated field
- dry cropland
- garden land
- arbor forest
- shrub forest
- park
- natural meadow
- artificial meadow
- river
- urban residential
- lake
- pond
- fish pond
- snow
- bareland
- rural residential
- stadium
- square
- road
- overpass
- railway station
- airport
distribution:
  - 0.
  - 0.0368
  - 0.0253
  - 0.3567
  - 0.0752
  - 0.0095
  - 0.0694
  - 0.0096
  - 0.0004
  - 0.0055
  - 0.0025
  - 0.0568
  - 0.0548
  - 0.1396
  - 0.0102
  - 0.0129
  - 0.0004
  - 0.0456
  - 0.0447
  - 0.0003
  - 0.0002
  - 0.0383
  - 0.0025
  - 0.0007
  - 0.0011

bands:
  optical:
    - B8
    - B4
    - B3
    - B2
data_mean:
  optical:
    - 92.6
    - 124.3
    - 94.2
    - 98.
data_std:
  optical:
    - 44.5
    - 51.
    - 50.
    - 47.1
data_min:
  optical: [0.0000, 0.0000, 0.0000, 0.0000]
data_max:
  optical: [0.0000, 0.0000, 0.0000, 0.0000]
