_target_: pangaea.datasets.xview2.xView2
dataset_name: xView2
root_path: ./data/xView2
download_url: https://the-dataset-is-not-publicly-available.com
auto_download: False
img_size: 1024
multi_temporal: False
multi_modal: False
oversample_building_damage: True

# classes
ignore_index: -1
num_classes: 5
classes:
  - No building
  - No damage
  - Minor damage
  - Major damage
  - Destroyed
distribution:
  - 0.9415
  - 0.0448
  - 0.0049
  - 0.0057
  - 0.0031

bands:
  optical:
    - B4
    - B3
    - B2
data_mean:
  optical:
    - 66.7703
    - 88.4452
    - 85.1047
data_std:
  optical:
    - 48.3066
    - 51.9129
    - 62.7612
data_min:
  optical: [0.0, 0.0, 0.0]
data_max:
  optical: [255, 255, 255]