encoder_name: gfm_swin
encoder_weights: ./pretrained_models/gfm.pth
encoder_model_args:
  img_size: 128
  embed_dim: 128
  in_chans: 3
  depths: [ 2, 2, 18, 2 ]
  num_heads: [ 4, 8, 16, 32 ]
  patch_size: 4
  window_size: 4
  drop_path_rate: 0.1