encoder_name: RemoteCLIP_Encoder
foundation_model_name: RemoteCLIP-ViT-B-32
encoder_weights: ./pretrained_models/RemoteCLIP-ViT-B-32.pt
download_url: https://huggingface.co/chendelong/RemoteCLIP/resolve/main/RemoteCLIP-ViT-B-32.pt
temporal_input: False

num_layers: 12
embed_dim: 768
input_size: 224

encoder_model_args:
  img_size: 224
  layers: 12
  width: 768
  head_width: 64
  patch_size: 32
  mlp_ratio: 4.0
  #check if to add other parameters (so far is useless)

input_bands:
  optical:
    - B4
    - B3
    - B2

output_layers:
  - 3
  - 5
  - 7
  - 11