encoder_config: configs/models_config/spectral_gpt.yaml
dataset_config: configs/datasets_config/mados_tiny.yaml
task_config: configs/tasks_config/segmentation.yaml
mode: train
epochs: 80
weight_param: 1.03
label_smoothing: 0.0
clip_grad: null
lr: 1.0e-3
decay: 0
reduce_lr_on_plateau: 0
lr_steps: [45,65]
eval_every: 1
save_every: 5
resume_from: null   
