train:
  RegPreprocessor: ~
  NormalizeMinMax: ~
  NormalizeMeanStd: ~
  RandomCropToEncoder: ~
#   RandomFlip:
#     ud_probability: 0.3
#     lr_probability: 0.3
test:
  RegPreprocessor: ~
  NormalizeMinMax: ~
  NormalizeMeanStd: ~
  Tile: ~
