dataset_name: mados
data_path: ./data/MADOS
num_classes: 15
multi_temporal: false
multi_modal: false
bands:
  - B2
  - B3
  - B4
  - B5
  - B6
  - B7
data_mean:
  - 775.2290211032589
  - 1080.992780391705
  - 1228.5855250417867
  - 2497.2022620507532
  - 2204.2139147975554
  - 1610.8324823273745
data_std:
  - 1281.526139861424
  - 1270.0297974547493
  - 1399.4802505642526
  - 1368.3446143747644
  - 1291.6764008585435
  - 1154.505683480695
data_loader:
  batch: 2
  num_workers: 0
  pin_memory: False
  prefetch_factor: null
  persistent_workers: False